apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Dev overlay: tiny replicas, image tag pinned to 'dev'.
images:
  - name: ghcr.io/vanshitahujaa/shortener-api
    newTag: dev
  - name: ghcr.io/vanshitahujaa/shortener-worker
    newTag: dev

patches:
  - target:
      kind: Deployment
      name: api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
